name: 'Action from Docker'
description: 'Generates 2 Random Integers and Prints Them to File'
inputs:
  name-of-file: 
    description: 'The name that will be given to the file'
    required: true
    default: 'Numbers.txt'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name-of-file }}