name: Docker and JavaScript Custom Actions

on:
  push

jobs:
  Custom-Docker-Action:
    runs-on: ubuntu-latest
    name: Custom Docker Action
    steps:
      - uses: actions/checkout@v2
      - name: Run Image
        uses: ./.github/actions/docker-action
        with:
          name-of-file: 'Numbers-By-Docker.txt'
      - name: Uploading Artifact
        uses: actions/upload-artifact@v2
        with:
          name: randomNumbers
          path: /home/runner/work/project-3-group_8/project-3-group_8/Numbers-By-Docker.txt
  Custom-JavaScript-Action:
    runs-on: ubuntu-latest
    needs: Custom-Docker-Action
    name: Custom JavaScript Action
    steps: 
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: randomNumbers
      - name: Read File
        id: addition
        uses: ./.github/actions/js-action
        with:
          name-of-file: 'Numbers-By-Docker.txt'
      - name: Display Output
        run: echo "The file read ${{ steps.addition.outputs.final-result }}"
        