on:
  push

jobs:
  Custom-Docker-Action:
    runs-on: ubuntu-latest
    name: Custom Docker Action
    steps:
      - uses: actions/checkout@v1
      - name: Run Image
        uses: ./.github/actions/docker-action