on:
  push

jobs:
  Custom-Docker-Action:
    runs-on: ubuntu-latest
    name: Custom Docker Action
    steps:
      - uses: actions/checkout@v1
      - name: Run Image
        uses: ./.github/actions/docker-action
        with:
          name-of-file: 'Numbers-By-Docker.txt'
      - name: Uploading Artifact
        uses: actions/upload-artifact@v2
        with:
          name: randomNumbers
          path: /workspace/Numbers-By-Docker.txt
      - name: Confirmation Message
        run: echo "Artifact Uploaded"
        