# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-nodejs-12:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@cen4053-fall2021'
    - name: Install dependencies
      run: npm install
    - run: npm ci
    - run: npm test
    - run: npm publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
    
  test-nodejs-14:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@cen4053-fall2021'
    - name: Install dependencies
      run: npm install
    - run: npm ci
    - run: npm test
    - run: npm publish
    env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
