# This workflow will perform an automated labeling of pull requests! 

name: Pull Request Labelling 

on:
  pull_request

jobs:
  add-labels: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Actions Ecosystem Add Labels
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GH_AUTH_TOKEN }}
          labels: Successfully Labeled